// Copyright 2021 The Khronos Group
// SPDX-License-Identifier: Apache-2.0

// This file was generated by generate_device_frontend.py from DeviceObject.h

#pragma once

#include "TreeObject.h"
#include "TreeObjects.h"

namespace anari_sdk{
namespace tree{


template <>
class Object<Device> : public DefaultObject<Device>
{
public:
  Object(ANARIDevice d, ANARIObject handle);
  int getProperty(const char *propname,
    ANARIDataType type,
    void *mem,
    uint64_t size,
    ANARIWaitMask mask) override;

};

} //namespace tree
} //namespace anari_sdk

