// Copyright 2021 The Khronos Group
// SPDX-License-Identifier: Apache-2.0

// This file was generated by generate_device_frontend.py from Specializations.h

#pragma once
#include "TreeDevice.h"

#include "TreeArrayObjects.h"
#include "TreeFrameObject.h"


#include <cstdio>

namespace anari_sdk{
namespace tree{


} //namespace tree
} //namespace anari_sdk

