#!/bin/bash

STB_IMAGE_WRITE_PATH=
ANARI_INSTALL_PATH=
ANARI_LIBRARY_PATH=${ANARI_INSTALL_PATH}/lib
ANARI_INCLUDE_PATH=${ANARI_INSTALL_PATH}/include

TRACE_PATH=$1

g++ -g trace_wrapper.cpp -o trace -lanari -L ${ANARI_LIBRARY_PATH} -I ${ANARI_INCLUDE_PATH} -I ${STB_IMAGE_WRITE_PATH} -I ${TRACE_PATH} -DTRACE_PATH="\"${TRACE_PATH}\""
