// This file was generated by $generator from $template

#pragma once

#include "$prefixObject.h"
#include "$prefixObjects.h"

#include <vector>

$begin_namespaces

template<>
class Object<Frame> : public FrameObjectBase {
   Frame staging;
   Frame current;
   std::vector<char> color;
   std::vector<float> depth;
public:
   Object(ANARIDevice d, ANARIObject handle);

   bool set(const char *paramname, ANARIDataType type, const void *mem) override;
   void unset(const char *paramname) override;
   void commit() override;
   int getProperty(
      const char *propname, ANARIDataType type,
      void *mem, uint64_t size, ANARIWaitMask mask) override;
   void* mapFrame(const char*) override;
   void unmapFrame(const char*) override;
   void renderFrame() override;
   void discardFrame() override;
   int frameReady(ANARIWaitMask mask) override;

   ANARIDataType type() const override { return Frame::type; }
   const char* subtype() const override { return Frame::subtype; }
   ParameterPack& parameters() override { return current; }
};

$end_namespaces
