#pragma once

#include <pxr/pxr.h>
#include <pxr/base/tf/debug.h>

PXR_NAMESPACE_OPEN_SCOPE

TF_DEBUG_CODES(
    HD_ANARI_RENDERDELEGATE,
    HD_ANARI_RENDERPASS,
    HD_ANARI_INSTANCER,
    HD_ANARI_MATERIAL
);

PXR_NAMESPACE_CLOSE_SCOPE
