name: ANARI-SDK CI

on:
  push:
    branches: [ next_release ]
  pull_request:
    branches: [ main, next_release ]

env:
  ANARI_LIBRARY: helide

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        config: [Release, Debug]

    steps:
    - uses: actions/checkout@v3

    - name: Install Packages
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt install -y libboost-system-dev

    - name: Configure CMake
      run: >
        cmake -LA -B ${{ github.workspace }}/build
        -DCMAKE_BUILD_TYPE=${{ matrix.config }}
        -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/build/install
        -DBUILD_SHARED_LIBS=ON
        -DBUILD_CTS=ON
        -DBUILD_EXAMPLES=ON
        -DBUILD_HDANARI=OFF
        -DBUILD_HELIDE_DEVICE=ON
        -DBUILD_REMOTE_DEVICE=${{ matrix.os == 'ubuntu-latest' }}
        -DBUILD_TESTING=ON
        -DBUILD_VIEWER=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.config }} --target install

    - name: Unit Tests
      working-directory: ${{ github.workspace }}/build
      run: ctest -R unit_test -C ${{ matrix.config }}

    - name: Render Tests
      working-directory: ${{github.workspace}}/build
      run: ctest -R render_test -C ${{ matrix.config }}

    - name: Tutorial Tests
      working-directory: ${{github.workspace}}/build
      run: ctest -R anariTutorial -C ${{ matrix.config }}

  build-macos:
    # iOS is 10x expensive to run on GitHub machines, so only run if we know something else passed as well
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        config: [Release]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: >
        cmake -LA -B ${{ github.workspace }}/build
        -DCMAKE_BUILD_TYPE=${{ matrix.config }}
        -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/build/install
        -DBUILD_SHARED_LIBS=ON
        -DBUILD_EXAMPLES=ON
        -DBUILD_HDANARI=OFF
        -DBUILD_HELIDE_DEVICE=ON
        -DBUILD_REMOTE_DEVICE=OFF
        -DBUILD_TESTING=ON
        -DBUILD_VIEWER=OFF

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.config }} --target install

    - name: Unit Tests
      working-directory: ${{ github.workspace }}/build
      run: ctest -R unit_test -C ${{ matrix.config }}

    - name: Render Tests
      working-directory: ${{ github.workspace }}/build
      run: ctest -R render_test -C ${{ matrix.config }}

    - name: Tutorial Tests
      working-directory: ${{ github.workspace }}/build
      run: ctest -R anariTutorial -C ${{ matrix.config }}
