## Copyright 2021-2024 The Khronos Group
## SPDX-License-Identifier: Apache-2.0

name: ANARI-SDK CI

on:
  push:
    branches: [ next_release ]
  pull_request:
    branches: [ main, next_release ]

env:
  ANARI_LIBRARY: helide

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
        config: [Release, Debug]
        exclude:
          - os: ubuntu-20.04
            config: Debug
    steps:
    - name: Install Packages
      run: sudo apt install -y libboost-system-dev libpython3-dev
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build and test
      uses: ./.github/actions/configure_and_build
      with:
        workspace: ${{ github.workspace }}
        config: ${{ matrix.config }}
        os: ${{ matrix.os }}
        shell: bash
    - name: Upload install
      if: ${{ matrix.config == 'Release' && matrix.os == 'ubuntu-20.04' }}
      uses: actions/upload-artifact@v4
      with:
        name: ANARI-SDK_${{ matrix.os }}
        path: ${{ github.workspace }}/build/install

  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        config: [Release, Debug]
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build and test
      uses: ./.github/actions/configure_and_build
      with:
        workspace: ${{ github.workspace }}
        config: ${{ matrix.config }}
        os: ${{ matrix.os }}
        shell: pwsh
    - name: Upload install
      if: ${{ matrix.config == 'Release' }}
      uses: actions/upload-artifact@v4
      with:
        name: ANARI-SDK_${{ matrix.os }}
        path: ${{ github.workspace }}/build/install

  build-macos:
    # iOS is 10x expensive to run on GitHub machines, so only run if we know something else passed as well
    needs: [build-linux, build-windows]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        config: [Release]
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build and test
      uses: ./.github/actions/configure_and_build
      with:
        workspace: ${{ github.workspace }}
        config: ${{ matrix.config }}
        os: ${{ matrix.os }}
        shell: bash
    - name: Upload install
      if: ${{ matrix.config == 'Release' }}
      uses: actions/upload-artifact@v4
      with:
        name: ANARI-SDK_${{ matrix.os }}
        path: ${{ github.workspace }}/build/install
