name: ANARI-SDK CI

on:
  push:
    branches: [ next_release ]
  pull_request:
    branches: [ main, next_release ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        config: [Release, Debug]
    env:
      ANARI_LIBRARY: helide
      PYTHONPATH: ${{github.workspace}}/build/${{matrix.config}}

    steps:
    - uses: actions/checkout@v3

    - name: Install Packages
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt install -y libboost-system-dev

    - name: Configure CMake
      run: >
        cmake -LA -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{ matrix.config }}
        -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/install
        -DBUILD_SHARED_LIBS=ON
        -DBUILD_EXAMPLES=ON
        -DBUILD_HDANARI=OFF
        -DBUILD_HELIDE_DEVICE=ON
        -DBUILD_REMOTE_DEVICE=${{ matrix.os == 'ubuntu-latest' }}
        -DBUILD_TESTING=ON
        -DBUILD_VIEWER=OFF
        -DCTS_ENABLE_GLTF=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.config }} --target install

    - name: Unit Tests
      working-directory: ${{github.workspace}}/build
      run: ctest -R unit_test -C ${{ matrix.config }}

    - name: Render Tests
      working-directory: ${{github.workspace}}/build
      run: ctest -R render_test -C ${{ matrix.config }}

    - name: Tutorial Tests
      working-directory: ${{github.workspace}}/build
      run: ctest -R anariTutorial -C ${{ matrix.config }}

    - name: Build CTS
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.config }} --target anariCTSBackend
    
    - name: CTS test case creation Linux
      working-directory: ${{github.workspace}}/cts
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt install pipx
        pipx ensurepath
        pipx install poetry
        poetry install
        poetry shell
        python3 ./createTestCasesFromGltf.py
      
    - name: CTS test case creation Windows
      working-directory: ${{github.workspace}}/cts
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        python -m pip install --user pipx
        python -m pipx ensurepath
        pipx install poetry
        poetry install
        poetry shell
        python ./createTestCasesFromGltf.py

    - name: CTS test case creation MacOS
      working-directory: ${{github.workspace}}/cts
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install pipx
        pipx ensurepath
        pipx install poetry
        poetry install
        poetry shell
        python3 ./createTestCasesFromGltf.py

    - name: CTS create reference data Linux
      working-directory: ${{github.workspace}}/cts
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        poetry install
        poetry shell
        python3 ./createReferenceData.py
        
    - name: CTS reate reference data Windows
      working-directory: ${{github.workspace}}/cts
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        poetry install
        poetry shell
        python ./createReferenceData.py

    - name: CTS create reference data MacOS
      working-directory: ${{github.workspace}}/cts
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        poetry install
        poetry shell
        python3 ./createReferenceData.py
